version: "4"
services:
  yukki:
    build: .
    environment:
      API_ID: $6960257
      API_HASH: $b94a7959955b4c85a33586416e2b9aa9
      BOT_TOKEN: $1988535912:AAFvGwDFyBnH5aBGRdvWqSV0neMfxlEaCro
      MONGO_DB_URI: $mongodb+srv://GANDDEDO:LUNDLELE@cluster0.tae5r.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      LOG_GROUP_ID: $-1001658407031
      MUSIC_BOT_NAME: $ABHI MUSIC
      OWNER_ID: $5289852546
      STRING_SESSION: $BQCxUqVAz9YZ8QCWFLiBqsygEExOZd08LmpmDzZH0e4I4vJeVyWL9bfdO2Mts2WUf7K8vhk32nZZN3ORCdRNUz1Qv5eWwSFbVTMH1-0Tkm-vDSZ-__YjOPoM9jAh_jakIJPCTqRIAkriDiNB1RZm91osSInpw39YzXQIWa2JiL5nqokUUS3hlmtlwFo2aHHBIqKIiuV6Y1tCS_tl6ZVITJ4HhgnrFQogIwKvTc3LW2qrEQ6KNnUljP5_8rWiA_1lkKGgWSg83ZTHEa-g8-z2qR5Ip5zUi9_NJI8ndHO1Hz5-bwW4THjoF-dILCzmfshccm23w_IQYOeskrEXzaeUI8yXAAAAAT1yGuwA
      DURATION_LIMIT: $500
